version: "3.0"

services:
  postgres:
    image: mariadb:10.5
    restart: always
    env_file: ./api/.docker.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skroutzdb
    ports:
      - 8080:8080
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
  backend:
    env_file: "./api/.docker.env"
    build:
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    links:
      - "mariadb:db"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    links:
      - "backend:be"
volumes:
  mysql-dump:
