################################ USER #####################################

# Send Request
# Create profile
# POST http://localhost:8080/user/create_profile
# Content-Type: application/x-www-form-urlencoded

# username=paris123&passowrd=1234&email=p@1.com&phone=6988702424
POST  http://localhost:8080/user/create_profile
Content-Type: application/json

{

    "username": "xaris",
    "password": "123",
    "email": "x@p.com",
    "name": "xaris",
    "surname": "potas",
    "phone": "",
    "address": "ed1",
    "zipcode": "123",
    "bellname": "xaris",
    "details": "o xaris o man"
}
### 
# LOGIN request
POST  http://localhost:8080/user/login

{
    "email": "xaris@potas.com",
    "password": "123"
}

################################ PRODUCTS #####################################
# Create Product Choice
# Post Request
POST http://localhost:8080/products/create_product_choice
Content-Type: application/json

{
    "name": "galaa",
    "description": "posi zaxari",
    "choices": [
        {
            "name": "sketo",
            "description": "sket",
            "price": 0
        },
        {
            "name": "metrio",
            "description": "sket",
            "price": 1.0
        }
    ],
    "for_classes": [
        "Tsai"
    ]
}

### 
# Create Product Category
# Post Request
POST http://localhost:8080/product_category/create_product_category
Content-Type: application/json

{
    "name": "Kafedes",
    "description": "Kafedes",
    "choices":[
        {
            "name":  "zaxar",
            "description":"poso zaxar",
            "options": [
                {
                "name":"sketos",
                "price":0
            }, {
                "name":"metrios",
                "price":1
            }]
        }
    ]
}

### 
# Create Product Ingredient
# Post Request
POST http://localhost:8080/products/create_product_ingredient
Content-Type: application/json

{
    "name": "zabon",
    "description": "alantikon",
    "price": 1.3
}

### 
# Create Product 
# Post Request
POST http://localhost:8080/products/create_product
Content-Type: application/json

{
    "name": "Teaaa",
    "description": "Teatime",
    "price": 2.2,
    "category": "Tsagia"
}

### 
# GET choices 
# GET Request
GET http://localhost:8080/products/choices
Content-Type: application/json

### 
# GET categories 
# GET Request
GET http://localhost:8080/products/categories
Content-Type: application/json


################################ ORDERS #####################################
# CREATE order
# POST Request
POST http://localhost:8080/orders/send_order
Content-Type: application/json

{
    "Product_Ids": [
        "5ff34efaf2bb393287fdd4ec",
        "5ff34f00f2bb393287fdd4ed"
    ],
    "User_id": "5ff34eebf2bb393287fdd4e9",
    "Payment_Type": "Cash and roll",
    "Tips": 2.5
}

############### COMMENTS  ################

# Post comment
# POST Request
POST http://localhost:8080/orders/post_comment
Content-Type: application/json

{
    "Text": "Nice oneeee",
    "UserID": "5ff348f3d7ac691f016b0d9e"
}