// REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

// LOGIN/LOGOUT
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// USER
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const UPDATE_USER = "UPDATE_USER";
export const GET_USERS = "GET_USERS";

// ERRORS
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const AUTH_ERROR = "AUTH_ERROR";

// PRODUCTS - CATEGORIES - INGREDIENTS
export const GET_ITEMS = "GET_ITEMS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_INGREDIENTS = "GET_INGREDIENTS";

export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_INGREDIENT = "CREATE_INGREDIENT";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";

export const CHANGE_AVAILABILITY = "CHANGE_AVAILABILITY";

// ORDERS
export const SEND_ORDER = "SEND_ORDER";
export const ACCEPT_ORDER = "ACCEPT_ORDER";
export const ORDER_ACCEPTED = "ORDER_ACCEPTED";
export const ORDER_DECLINED = "ORDER_DECLINED";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
// export const ADD_ITEM = "ADD_ITEM";
